import type { Ficha } from '../api/types'

export function criarFichaFake(overrides: Partial<Ficha> = {}): Ficha {
  return {
    id: 'ficha-1',
    geral: {
      nomePersonagem: 'Aria Ventoclaro',
      classe: 'Ladina',
      nivel: 3,
      raca: 'Elfa',
      alinhamento: 'Caótico e Bom',
      divindade: '',
      tamanho: 'Médio',
      genero: 'Feminino',
      idade: '120',
      altura: '1,60m',
      peso: '50kg',
      idiomas: 'Comum, Élfico',
      str: 10,
      dex: 18,
      con: 12,
      int: 14,
      wis: 10,
      cha: 8,
    },
    combate: {
      pvMax: 20,
      pvAtual: 20,
      pvTemp: 0,
      dadosDeVida: '3d6',
      caTotal: 16,
      caToque: 14,
      caSurpreendido: 12,
      caArmadura: 2,
      caEscudo: 0,
      caDestreza: 4,
      caTamanho: 0,
      caNatural: 0,
      caDesvio: 0,
      caOutros: 0,
      fortBase: 1,
      fortMagico: 0,
      fortOutros: 0,
      reflexosBase: 3,
      reflexosMagico: 0,
      reflexosOutros: 0,
      vontadeBase: 1,
      vontadeMagico: 0,
      vontadeOutros: 0,
      bab: 2,
      deslocamento: 9,
      iniciativaOutros: 0,
      iniciativaTotal: 4,
      agarraoOutros: 0,
      corpoACorpoOutros: 0,
      distanciaOutros: 0,
      cmbTotal: 0,
      cmbOutros: 0,
      cmdTotal: 0,
      cmdOutros: 0,
    },
    magiasConfig: { atributoConjuracao: 'INT', nivelConjurador: 0, cdOutros: 0 },
    moedas: { pp: 0, gp: 15, sp: 0, cp: 0, cargaLeve: 0, cargaMedia: 0, cargaPesada: 0, pesoTotalCarregado: 0 },
    notas: { texto: '' },
    talentos: [{ id: 't1', nome: 'Ataque Furtivo', descricao: '+2d6 de dano', categoria: 'talento' }],
    ataques: [
      {
        id: 'a1',
        arma: 'Adaga',
        bonus: '+5',
        dano: '1d4',
        critico: '19-20/x2',
        tipo: 'Perfurante',
        alcance: '3m',
        peso: 0.5,
        tamanho: 'Pequena',
        propriedadesEspeciais: '',
      },
    ],
    pericias: [
      { id: 'p1', nome: 'Furtividade', atributo: 'DEX', periciaDeClasse: true, graduacoes: 6, outros: 0, total: 10 },
    ],
    magiaNiveis: Array.from({ length: 10 }, (_, nivel) => ({
      id: String(nivel),
      nivel,
      espacosPorDia: null,
      magiasAdicionais: null,
      magiasConhecidas: null,
    })),
    magias: [],
    itens: [{ id: 'i1', nome: 'Corda de seda', quantidade: 1, peso: 2, notas: '15m' }],
    ...overrides,
  }
}
