import { describe, expect, it } from 'vitest'
import { mapObjectToFrontend, mapPatchToBackend } from './wireFormat'

describe('wireFormat', () => {
  it('converte campos snake_case da API para camelCase do frontend', () => {
    expect(
      mapObjectToFrontend({
        id: 'g1',
        ficha_id: 'f1',
        nome_personagem: 'Aria',
        pv_maximo: 20,
        pv_temporario: 0,
        fortitude_base: 1,
        fortitude_magico: 0,
        fortitude_outros: 0,
        corpo_a_corpo_outros: 2,
        pericia_de_classe: true,
        espacos_por_dia: 3,
        cmb_total: 9,
        cmb_outros: 0,
        cmd_total: 22,
        cmd_outros: 0,
        teste_resistencia: 'Vontade parcial',
        resistencia_magia: 'Sim',
        alvo_efeito: 'Um alvo',
        tempo_formulacao: '1 ação padrão',
        propriedades_especiais: 'Cortante',
        magias_adicionais: 1,
        magias_conhecidas: 4,
        carga_leve: 33,
        carga_media: 66,
        carga_pesada: 100,
        peso_total_carregado: 12.5,
      }),
    ).toEqual({
      id: 'g1',
      nomePersonagem: 'Aria',
      pvMax: 20,
      pvTemp: 0,
      fortBase: 1,
      fortMagico: 0,
      fortOutros: 0,
      corpoACorpoOutros: 2,
      periciaDeClasse: true,
      espacosPorDia: 3,
      cmbTotal: 9,
      cmbOutros: 0,
      cmdTotal: 22,
      cmdOutros: 0,
      testeResistencia: 'Vontade parcial',
      resistenciaMagia: 'Sim',
      alvoEfeito: 'Um alvo',
      tempoFormulacao: '1 ação padrão',
      propriedadesEspeciais: 'Cortante',
      magiasAdicionais: 1,
      magiasConhecidas: 4,
      cargaLeve: 33,
      cargaMedia: 66,
      cargaPesada: 100,
      pesoTotalCarregado: 12.5,
    })
  })

  it('converte campos camelCase do frontend para snake_case da API', () => {
    expect(
      mapPatchToBackend({
        nomePersonagem: 'Aria',
        pvMax: 20,
        pvTemp: 0,
        fortBase: 1,
        fortMagico: 0,
        fortOutros: 0,
        corpoACorpoOutros: 2,
        periciaDeClasse: true,
        espacosPorDia: 3,
        cmbTotal: 9,
        cmbOutros: 0,
        cmdTotal: 22,
        cmdOutros: 0,
        testeResistencia: 'Vontade parcial',
        resistenciaMagia: 'Sim',
        alvoEfeito: 'Um alvo',
        tempoFormulacao: '1 ação padrão',
        propriedadesEspeciais: 'Cortante',
        magiasAdicionais: 1,
        magiasConhecidas: 4,
        cargaLeve: 33,
        cargaMedia: 66,
        cargaPesada: 100,
        pesoTotalCarregado: 12.5,
      }),
    ).toEqual({
      nome_personagem: 'Aria',
      pv_maximo: 20,
      pv_temporario: 0,
      fortitude_base: 1,
      fortitude_magico: 0,
      fortitude_outros: 0,
      corpo_a_corpo_outros: 2,
      pericia_de_classe: true,
      espacos_por_dia: 3,
      cmb_total: 9,
      cmb_outros: 0,
      cmd_total: 22,
      cmd_outros: 0,
      teste_resistencia: 'Vontade parcial',
      resistencia_magia: 'Sim',
      alvo_efeito: 'Um alvo',
      tempo_formulacao: '1 ação padrão',
      propriedades_especiais: 'Cortante',
      magias_adicionais: 1,
      magias_conhecidas: 4,
      carga_leve: 33,
      carga_media: 66,
      carga_pesada: 100,
      peso_total_carregado: 12.5,
    })
  })
})
